<?php

namespace PlatBundle\Repository;

/**
 * specialiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class specialiteRepository extends \Doctrine\ORM\EntityRepository
{
}
