<?php

namespace PlatBundle\Repository;

/**
 * TypeplatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeplatRepository extends \Doctrine\ORM\EntityRepository
{
}
