<?php

namespace PlatBundle\Repository;

/**
 * UstensilesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UstensilesRepository extends \Doctrine\ORM\EntityRepository
{
}
