plat:
    resource: "@PlatBundle/Resources/config/routing.yml"
    prefix:   /plat

maladie:
    resource: "@MaladieBundle/Resources/config/routing.yml"
    prefix:   /maladie

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
