plat_index:
    path:     /
    defaults: { _controller: "ProjectBundle:Plat:index" }
    methods:  GET

plat_show:
    path:     /{id}/show
    defaults: { _controller: "ProjectBundle:Plat:show" }
    methods:  GET

plat_new:
    path:     /new
    defaults: { _controller: "ProjectBundle:Plat:new" }
    methods:  [GET, POST]

plat_edit:
    path:     /{id}/edit
    defaults: { _controller: "ProjectBundle:Plat:edit" }
    methods:  [GET, POST]

plat_delete:
    path:     /{id}/delete
    defaults: { _controller: "ProjectBundle:Plat:delete" }
    methods:  DELETE
