typeplat_index:
    path:     /
    defaults: { _controller: "ProjectBundle:Typeplat:index" }
    methods:  GET

typeplat_show:
    path:     /{id}/show
    defaults: { _controller: "ProjectBundle:Typeplat:show" }
    methods:  GET

typeplat_new:
    path:     /new
    defaults: { _controller: "ProjectBundle:Typeplat:new" }
    methods:  [GET, POST]

typeplat_edit:
    path:     /{id}/edit
    defaults: { _controller: "ProjectBundle:Typeplat:edit" }
    methods:  [GET, POST]

typeplat_delete:
    path:     /{id}/delete
    defaults: { _controller: "ProjectBundle:Typeplat:delete" }
    methods:  DELETE
