ustensilles_index:
    path:     /
    defaults: { _controller: "ProjectBundle:Ustensilles:index" }
    methods:  GET

ustensilles_show:
    path:     /{idUst}/show
    defaults: { _controller: "ProjectBundle:Ustensilles:show" }
    methods:  GET

ustensilles_new:
    path:     /new
    defaults: { _controller: "ProjectBundle:Ustensilles:new" }
    methods:  [GET, POST]

ustensilles_edit:
    path:     /{idUst}/edit
    defaults: { _controller: "ProjectBundle:Ustensilles:edit" }
    methods:  [GET, POST]

ustensilles_delete:
    path:     /{idUst}/delete
    defaults: { _controller: "ProjectBundle:Ustensilles:delete" }
    methods:  DELETE
