<?php

namespace ProjectBundle\Repository;

/**
 * NotesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotesRepository extends \Doctrine\ORM\EntityRepository
{
}
