<?php

namespace ProjectBundle\Repository;

/**
 * PlatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlatRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAvecAutres()
    {
        return  $this->getEntityManager()
            ->createQuery('
            SELECT p,n FROM ProjectBundle:plat p
            LEFT JOIN p.note n'

            )
            ->getResult();



    }


}
