<?php

namespace ProjectBundle\Repository;

/**
 * UstensillesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UstensillesRepository extends \Doctrine\ORM\EntityRepository
{
}
