<?php

namespace MaladieBundle\Repository;

/**
 * MaladieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MaladieRepository extends \Doctrine\ORM\EntityRepository
{
}
