<?php

namespace MaladieBundle\Repository;

/**
 * MaladieUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MaladieUserRepository extends \Doctrine\ORM\EntityRepository
{
}
