project_plat:
    resource: "@ProjectBundle/Resources/config/routing/plat.yml"
    prefix:   /plat

project_ustensilles:
    resource: "@ProjectBundle/Resources/config/routing/ustensilles.yml"
    prefix:   /ustensilles

project_specialite:
    resource: "@ProjectBundle/Resources/config/routing/specialite.yml"
    prefix:   /specialite

project_typeplat:
    resource: "@ProjectBundle/Resources/config/routing/typeplat.yml"
    prefix:   /typeplat

project_note:
    resource: "@ProjectBundle/Resources/config/routing/note.yml"
    prefix:   /note

project_homepage:
    path:     /homepage
    defaults: { _controller: ProjectBundle:Default:index }
